const express = require('express');
const router = express.Router();
const { signup, signin } = require('../controllers/auth');
const {profile}=require('../controllers/profile');
const{getAllUsers}= require('../controllers/getAll');
const {getPet} = require('../controllers/getPet');
const {getAllPets} = require('../controllers/getAllPets');
router.post('/signup', signup);
router.post('/signin', signin);
router.put('/create', profile);
router.get('/getAllUsers',getAllUsers);
router.get('/getAllPets',getAllPets);
router.get('/getPet',getPet);
module.exports = router;