const express = require('express');
const router = express.Router();
const { signup, signin } = require('../controllers/auth');
const {profile}=require('../controllers/profile');
const{getAllUsers}= require('../controllers/getAll');
router.post('/signup', signup);
router.post('/signin', signin);
router.put('/create', profile);
router.get('/getAll',getAllUsers);
module.exports = router;